packages:
  - 'extensions/*'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - 'core-js'
  - 'esbuild'
  - 'msw'
  - 'prisma'
  - 'protobufjs'
  - 'unrs-resolver'
